sonar.organization=01211820sms
sonar.projectKey=walleyjay_xashy-university_portal
sonar.sources=src/main/java,src/main/webapp
sonar.tests=src/test/java
sonar.sourceEncoding=UTF-8
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
